version: '3.8'
services:
  selenium-hub:
    image: selenium/hub:4.20.0-20240505
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.20.0-20240505
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3
    ports:
      - "6900:5900"

  edge:
    image: selenium/node-edge:4.20.0-20240505
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3
    ports:
      - "6901:5900"

  firefox:
    image: selenium/node-firefox:4.20.0-20240505
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3
    ports:
      - "6902:5900"

  phpunit:
    build: .
    depends_on:
      - selenium-hub
      - chrome
      - edge
      - firefox
    environment:
      - SELENIUM_HUB_URL=http://selenium-hub:4444/wd/hub/status
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    entrypoint: ["entrypoint.sh"]
    command: ["vendor/bin/phpunit", "--configuration", "phpunit-selenium/phpunit.xml"]
